import { useEffect, useState } from 'react';
import '../../styles/superAdminUploadedPatch2.css';
import '../../styles/superAdminUploadedPatch3.css';

const nav = [
  ['Overview','dashboard','▦'],['Companies','companies','⌂'],['Users & Roles','users-roles','♙'],['Subscriptions','subscriptions','₹'],['Revenue & Plans','revenue-plans','▥'],['Leads Monitor','leads-monitor','◎'],['Demo Requests','demo-requests','✉'],['Website Health','website-health','◎'],['Notifications','notifications','♢'],['Email Logs','email-logs','✉'],['Security','security','◇'],['Platform Settings','platform-settings','⚙'],['Reports','reports','▤'],['Activity Logs','activity-logs','☷'],['Support Tickets','support-tickets','?']
];
const titleMap = {dashboard:['Overview Dashboard','Platform command center for companies, users, demos, revenue and website health.'],companies:['Companies','Manage companies, owners, plans, trial status and activation.'],'users-roles':['Users & Roles','Monitor platform users, roles and access status.'],subscriptions:['Subscriptions','Manage trials, paid plans, billing and expiry risk.'],'revenue-plans':['Revenue & Plans','Revenue summary, plan mix and growth performance.'],'leads-monitor':['Leads Monitor','Track CRM leads across all companies.'],'demo-requests':['Demo Requests','Landing page Book Demo submissions from customers.'],'website-health':['Website Health','Monitor website, app, SSL, uptime and response time.'],notifications:['Notifications','System notifications and alerts.'],'email-logs':['Email Logs','OTP, demo alert and report email logs.'],security:['Security','Access, security and platform protection overview.'],'platform-settings':['Platform Settings','Global platform configuration.'],reports:['Reports','Export companies, users, demos and revenue reports.'],'activity-logs':['Activity Logs','Audit trail of user, demo and platform activity.'],'support-tickets':['Support Tickets','Client issues, tickets and follow-up queue.']};
const aliases={users:'users-roles',roles:'users-roles',billing:'subscriptions',settings:'platform-settings'};
const go=(v)=>{window.history.pushState({},'',`/super-admin/${v==='dashboard'?'dashboard':v}`);window.dispatchEvent(new Event('salesflow:navigate'));};
const date=(v)=>{const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-'};
const filter=(rows,q)=>{const s=String(q||'').toLowerCase();return !s?(rows||[]):(rows||[]).filter(r=>Object.values(r).join(' ').toLowerCase().includes(s));};
const tone=(v)=>/active|paid|sent|delivered|up|valid|converted|scheduled|won/i.test(v)?'green':/trial|pending|new|contacted|progress|degraded/i.test(v)?'orange':/expired|inactive|failed|down|open|rejected|lost|suspend/i.test(v)?'red':'blue';
function Badge({v}){return <span className={`sfsa-badge ${tone(v)}`}>{v||'-'}</span>}
function Empty(){return <div className="sfsa-empty">No records found.</div>}
function Stat({icon,label,value,hint}){return <article className="sfsa-stat"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{hint||'Live CRM'}</em></div></article>}
function Stats({data}){const s=data.stats||{};return <section className="sfsa-stats"><Stat icon="🏢" label="Total Companies" value={s.totalCompanies||0}/><Stat icon="✅" label="Active Companies" value={s.activeCompanies||0}/><Stat icon="⏱" label="Trial Companies" value={s.trialCompanies||0}/><Stat icon="👥" label="Total Users" value={s.totalUsers||0} hint={`${s.activeUsers||0} active`}/><Stat icon="📥" label="Demo Requests" value={s.demoRequests||0}/><Stat icon="🎯" label="Total Leads" value={s.totalLeads||0}/><Stat icon="₹" label="Monthly Revenue" value={`₹${Number(s.monthlyRevenue||0).toLocaleString('en-IN')}`}/><Stat icon="⚡" label="Uptime" value={s.uptime||'99.98%'}/></section>}
function Panel({title,sub,action,children}){return <section className="sfsa-panel"><header><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</header>{children}</section>}
function Table({rows,cols}){return <div className="sfsa-table"><table><thead><tr>{cols.map(c=><th key={c.k}>{c.l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c.k}>{c.badge?<Badge v={r[c.k]}/>:c.date?date(r[c.k]):c.main?<><strong>{r[c.k]||'-'}</strong><small>{r[c.sub]||''}</small></>:r[c.k]??'-'}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>}
function Bars({items=[]}){const arr=items.length?items.map(x=>Math.max(26,Math.min(94,Number(x.users||x.value||5)*8))):[40,58,46,74,66,88,72,94];return <div className="sfsa-bars">{arr.map((h,i)=><i key={i} style={{'--h':`${h}%`}}/>)}</div>}
function Dots({items=[]}){const arr=items.length?items:Array.from({length:20},()=>1);return <div className="sfsa-dots">{arr.map((ok,i)=><i key={i} className={ok?'ok':'bad'}/>)}</div>}
function Overview({data,q}){const companies=filter(data.companies,q).slice(0,8),demos=filter(data.demoRequests,q).slice(0,6);return <><Stats data={data}/><section className="sfsa-grid two"><Panel title="Growth Overview" sub="Platform growth trend."><Bars items={data.growth||[]}/></Panel><Panel title="Website Health" sub="Public website and app monitor." action={<button onClick={()=>go('website-health')}>Open</button>}><div className="sfsa-list">{(data.websiteHealth||[]).slice(0,4).map(s=><div key={s.id}><b>{s.status==='Up'?'🟢':'🟠'} {s.company}</b><small>{s.url}</small><em>{s.responseTime}ms</em></div>)}</div></Panel></section><section className="sfsa-grid wide"><Panel title="Recent Companies" sub="Company plan and status." action={<button onClick={()=>go('companies')}>View All</button>}><Table rows={companies} cols={[{k:'name',l:'Company',main:1,sub:'adminEmail'},{k:'plan',l:'Plan',badge:1},{k:'status',l:'Status',badge:1},{k:'users',l:'Users'},{k:'createdAt',l:'Created',date:1}]}/></Panel><Panel title="Demo Requests" sub="Latest Book Demo submissions." action={<button onClick={()=>go('demo-requests')}>Open</button>}><div className="sfsa-list">{demos.map(d=><div key={d.id}><b>{d.fullName}</b><small>{d.companyName} · {d.email}</small><Badge v={d.status}/></div>)}{!demos.length&&<Empty/>}</div></Panel></section></>}
function Companies({data,q}){return <><Stats data={data}/><Panel title="Company Management" sub="Connected to CRM companies table."><Table rows={filter(data.companies,q)} cols={[{k:'name',l:'Company',main:1,sub:'adminEmail'},{k:'plan',l:'Plan',badge:1},{k:'status',l:'Status',badge:1},{k:'users',l:'Users'},{k:'trialDaysLeft',l:'Trial Days'},{k:'createdAt',l:'Created',date:1}]}/></Panel></>}
function Users({data,q}){return <><Stats data={data}/><Panel title="Users & Roles" sub="Connected platform profiles."><Table rows={filter(data.recentUsers,q)} cols={[{k:'name',l:'User',main:1,sub:'email'},{k:'companyName',l:'Company'},{k:'role',l:'Role',badge:1},{k:'isActive',l:'Active'},{k:'createdAt',l:'Created',date:1}]}/></Panel></>}
function Demos({data,q}){return <><Stats data={data}/><Panel title="Book Demo Requests" sub="Connected to Supabase demo_requests table."><Table rows={filter(data.demoRequests,q)} cols={[{k:'fullName',l:'Name',main:1,sub:'email'},{k:'mobile',l:'Mobile'},{k:'companyName',l:'Company'},{k:'teamSize',l:'Team'},{k:'requirement',l:'Need'},{k:'preferredTime',l:'Time'},{k:'status',l:'Status',badge:1},{k:'createdAt',l:'Created',date:1}]}/></Panel></>}
function Health({data,q}){return <><Stats data={data}/><Panel title="Website Health Monitor" sub="Uploaded health layout with CRM connected data."><div className="sfsa-sites">{filter(data.websiteHealth,q).map(s=><article key={s.id}><header><b>{s.status==='Up'?'🟢':'🟠'} {s.company}</b><Badge v={s.status}/></header><p>{s.url}</p><div><span><b>{s.uptime}</b><small>Uptime</small></span><span><b>{s.responseTime}ms</b><small>Response</small></span><span><b>{s.ssl}</b><small>SSL</small></span></div><Dots items={s.checks}/></article>)}</div></Panel></>}
function Generic({view,data,q}){const map={'leads-monitor':[data.leads||[],[{k:'leadName',l:'Lead',main:1,sub:'company'},{k:'assignedTo',l:'Assigned'},{k:'status',l:'Status',badge:1},{k:'followUp',l:'Follow-up'}]],notifications:[data.notifications||[],[{k:'title',l:'Title',main:1,sub:'company'},{k:'priority',l:'Priority',badge:1},{k:'status',l:'Status',badge:1},{k:'time',l:'Time'}]],'email-logs':[data.emailLogs||[],[{k:'type',l:'Type',main:1,sub:'subject'},{k:'to',l:'To'},{k:'status',l:'Status',badge:1},{k:'time',l:'Time'}]],'activity-logs':[data.activityLogs||[],[{k:'time',l:'Time'},{k:'name',l:'User',main:1,sub:'email'},{k:'company',l:'Company'},{k:'action',l:'Action',badge:1}]],'support-tickets':[data.supportTickets||[],[{k:'subject',l:'Subject',main:1,sub:'owner'},{k:'company',l:'Company'},{k:'priority',l:'Priority',badge:1},{k:'status',l:'Status',badge:1}]]};const [rows=[],cols=[]]=map[view]||[[],[]];return <><Stats data={data}/><Panel title={(titleMap[view]||titleMap.reports)[0]} sub={cols.length?'Connected CRM records.':'Platform configuration ready.'}>{cols.length?<Table rows={filter(rows,q)} cols={cols}/>:<div className="sfsa-sites">{['Trial 7 days','OTP enabled','Demo alerts enabled','Role based access','Company isolation','Export reports'].map(x=><article key={x}><header><b>{x}</b></header><p>Super Admin control ready.</p></article>)}</div>}</Panel></>}
function Layout({view,q,setQ,loading,load,children}){const title=titleMap[view]||titleMap.dashboard;return <div className="sfsa-root"><aside className="sfsa-sidebar"><div className="sfsa-brand"><div className="sfsa-logo">SH</div><div><strong>SalesFlow Hub</strong><small>Super Admin</small></div></div><nav>{nav.map(([label,route,icon])=><button key={route} className={view===route?'active':''} onClick={()=>go(route)}><span>{icon}</span><em>{label}</em>{label==='Notifications'&&<b>12</b>}{label==='Website Health'&&<b>4</b>}</button>)}</nav><footer><span/> <p>View Platform Status</p><small>© 2026 SalesFlow Hub<br/>All rights reserved.</small></footer></aside><main className="sfsa-main"><header className="sfsa-topbar"><div className="sfsa-search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search companies, users, invoices, tickets..."/><kbd>⌘K</kbd></div><div className="sfsa-date">May 12 – Jun 12, 2026</div><button className="sfsa-bell">🔔<b>8</b></button><button className="sfsa-help">?</button><div className="sfsa-profile"><span>SA</span><div><strong>Super Admin</strong><small>superadmin@salesflowhub.cloud</small></div></div></header><section className="sfsa-content"><div className="sfsa-title"><div><h1>{title[0]}</h1><p>{title[1]}</p></div><button onClick={load}>{loading?'Loading...':'Refresh'}</button></div>{children}</section></main></div>}
export default function SuperAdminPortalUploaded({view:rawView='dashboard'}){const view=aliases[rawView]||rawView||'dashboard';const [data,setData]=useState({stats:{},companies:[],recentUsers:[],demoRequests:[],websiteHealth:[]});const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const load=async()=>{try{setLoading(true);setMsg('');const r=await fetch('/api/super-admin-overview');const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.message||'Unable to load data');setData(j)}catch(e){setMsg(e.message||'Unable to load data')}finally{setLoading(false)}};useEffect(()=>{load()},[]);let page=view==='dashboard'?<Overview data={data} q={q}/>:view==='companies'?<Companies data={data} q={q}/>:view==='users-roles'?<Users data={data} q={q}/>:view==='demo-requests'?<Demos data={data} q={q}/>:view==='website-health'?<Health data={data} q={q}/>:<Generic view={view} data={data} q={q}/>;return <Layout view={view} q={q} setQ={setQ} loading={loading} load={load}>{msg&&<div className="sfsa-message">{msg}</div>}{page}</Layout>}
