import { useEffect, useState } from 'react';
import DashboardSidebar from '../../components/dashboard/DashboardSidebar.jsx';
import '../../styles/superAdminPortalSmall.css';

const meta={dashboard:['Overview Dashboard','Platform control center for companies, users, demo requests and website health.'],companies:['Companies','Company plan and status control.'],'users-roles':['Users & Roles','Platform users and roles.'],'demo-requests':['Demo Requests','Landing page Book Demo submissions.'],'website-health':['Website Health','Website, app, SSL and response monitor.'],'leads-monitor':['Leads Monitor','Company-wise CRM leads.'],subscriptions:['Subscriptions','Trials and billing.'],'revenue-plans':['Revenue & Plans','Revenue and plan mix.'],notifications:['Notifications','Platform alerts.'],'email-logs':['Email Logs','Email delivery logs.'],security:['Security','Access and protection.'],'activity-logs':['Activity Logs','Audit trail.'],'support-tickets':['Support Tickets','Client issues.'],reports:['Reports','Exports and reports.'],'platform-settings':['Platform Settings','Global configuration.']};
const aliases={users:'users-roles',roles:'users-roles',billing:'subscriptions',settings:'platform-settings'};
const viewOf=(v)=>aliases[v]||v||'dashboard';
const go=(v)=>{window.history.pushState({},'',`/super-admin/${v==='dashboard'?'dashboard':v}`);window.dispatchEvent(new Event('salesflow:navigate'));};
const dt=(v)=>{const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-'};
const find=(rows,q)=>{const s=String(q||'').toLowerCase();return !s?rows:(rows||[]).filter(r=>Object.values(r).join(' ').toLowerCase().includes(s));};
const tone=(x)=>/active|paid|sent|up|won|converted|scheduled/i.test(x)?'green':/trial|pending|new|contacted|degraded/i.test(x)?'orange':/expired|inactive|failed|down|lost|rejected/i.test(x)?'red':'blue';
function Badge({v}){return <span className={`sap2-badge ${tone(v)}`}>{v||'-'}</span>}
function Stat({i,t,v,h}){return <article className="sap2-stat"><span>{i}</span><div><small>{t}</small><strong>{v}</strong><em>{h||'Live CRM'}</em></div></article>}
function Box({title,sub,children,btn}){return <section className="sap2-panel"><header><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{btn}</header>{children}</section>}
function Table({rows,cols}){return <div className="sap2-table"><table><thead><tr>{cols.map(c=><th key={c.k}>{c.l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c.k}>{c.b?<Badge v={r[c.k]}/>:c.d?dt(r[c.k]):c.s?<><strong>{r[c.k]}</strong><small>{r[c.sub]||''}</small></>:r[c.k]||'-'}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="sap2-empty">No records found.</p>}</div>}
function Bars({a=[]}){const vals=a.length?a.map(x=>Math.max(26,Math.min(92,Number(x.users||5)*8))):[42,58,46,72,66,88,70,92];return <div className="sap2-bars">{vals.map((v,i)=><i key={i} style={{'--h':`${v}%`}}/> )}</div>}
function Dots({a=[]}){const list=a.length?a:Array.from({length:20},()=>1);return <div className="sap2-dots">{list.map((x,i)=><i key={i} className={x?'ok':'bad'}/>)}</div>}
function Stats({data}){const s=data.stats||{};return <div className="sap2-stats eight"><Stat i="🏢" t="Companies" v={s.totalCompanies||0}/><Stat i="✅" t="Active" v={s.activeCompanies||0}/><Stat i="⏱" t="Trial" v={s.trialCompanies||0}/><Stat i="👥" t="Users" v={s.totalUsers||0}/><Stat i="📥" t="Demos" v={s.demoRequests||0}/><Stat i="🎯" t="Leads" v={s.totalLeads||0}/><Stat i="₹" t="Revenue" v={`₹${Number(s.monthlyRevenue||0).toLocaleString('en-IN')}`}/><Stat i="⚡" t="Uptime" v={s.uptime||'99.98%'}/></div>}
function Dashboard({data,q}){const companies=find(data.companies||[],q).slice(0,8),demos=find(data.demoRequests||[],q).slice(0,6);return <><Stats data={data}/><div className="sap2-grid two"><Box title="Growth Overview" sub="Platform growth trend."><Bars a={data.growth}/></Box><Box title="Website Health" sub="Public website and app monitor." btn={<button onClick={()=>go('website-health')}>Open</button>}><div className="sap2-list">{(data.websiteHealth||[]).slice(0,4).map(x=><div key={x.id}><b>{x.status==='Up'?'🟢':'🟠'} {x.company}</b><small>{x.url}</small><em>{x.responseTime}ms</em></div>)}</div></Box></div><div className="sap2-grid wide"><Box title="Recent Companies" sub="Company plan and status." btn={<button onClick={()=>go('companies')}>View All</button>}><Table rows={companies} cols={[{k:'name',l:'Company',s:1,sub:'adminEmail'},{k:'plan',l:'Plan',b:1},{k:'status',l:'Status',b:1},{k:'users',l:'Users'},{k:'createdAt',l:'Created',d:1}]}/></Box><Box title="Demo Requests" sub="Latest Book Demo submissions." btn={<button onClick={()=>go('demo-requests')}>Open</button>}><div className="sap2-list">{demos.map(x=><div key={x.id}><b>{x.fullName}</b><small>{x.companyName} · {x.email}</small><Badge v={x.status}/></div>)}</div></Box></div></>}
function Companies({data,q}){return <><Stats data={data}/><Box title="Company Management" sub="Connected to CRM companies table."><Table rows={find(data.companies||[],q)} cols={[{k:'name',l:'Company',s:1,sub:'adminEmail'},{k:'plan',l:'Plan',b:1},{k:'status',l:'Status',b:1},{k:'users',l:'Users'},{k:'trialDaysLeft',l:'Trial Days'},{k:'createdAt',l:'Created',d:1}]}/></Box></>}
function Users({data,q}){return <><Stats data={data}/><Box title="Users & Roles" sub="Connected platform profiles."><Table rows={find(data.recentUsers||[],q)} cols={[{k:'name',l:'User',s:1,sub:'email'},{k:'companyName',l:'Company'},{k:'role',l:'Role',b:1},{k:'isActive',l:'Active'},{k:'createdAt',l:'Created',d:1}]}/></Box></>}
function Demos({data,q}){return <><Stats data={data}/><Box title="Book Demo Requests" sub="Connected to Supabase demo_requests table."><Table rows={find(data.demoRequests||[],q)} cols={[{k:'fullName',l:'Name',s:1,sub:'email'},{k:'mobile',l:'Mobile'},{k:'companyName',l:'Company'},{k:'teamSize',l:'Team'},{k:'requirement',l:'Need'},{k:'preferredTime',l:'Time'},{k:'status',l:'Status',b:1},{k:'createdAt',l:'Created',d:1}]}/></Box></>}
function Health({data,q}){return <><Stats data={data}/><Box title="Website Health Monitor" sub="Same uploaded health layout, connected to platform data."><div className="sap2-sites">{find(data.websiteHealth||[],q).map(x=><article key={x.id}><header><b>{x.status==='Up'?'🟢':'🟠'} {x.company}</b><Badge v={x.status}/></header><p>{x.url}</p><div><span><b>{x.uptime}</b><small>Uptime</small></span><span><b>{x.responseTime}ms</b><small>Response</small></span><span><b>{x.ssl}</b><small>SSL</small></span></div><Dots a={x.checks}/></article>)}</div></Box></>}
function Generic({view,data,q}){const rows={ 'leads-monitor':data.leads||[], notifications:data.notifications||[], 'email-logs':data.emailLogs||[], 'activity-logs':data.activityLogs||[], 'support-tickets':data.supportTickets||[] }[view]||[];return <><Stats data={data}/><Box title={(meta[view]||meta.reports)[0]} sub="Connected CRM records."><Table rows={find(rows,q)} cols={[{k:'title',l:'Title',s:1,sub:'company'},{k:'leadName',l:'Lead',s:1,sub:'company'},{k:'subject',l:'Subject',s:1,sub:'owner'},{k:'email',l:'Email'},{k:'status',l:'Status',b:1},{k:'time',l:'Time'},{k:'createdAt',l:'Created',d:1}]}/></Box></>}
export default function SuperAdminPortal({view:raw='dashboard'}){const view=viewOf(raw);const [data,setData]=useState({stats:{}});const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const load=async()=>{try{setLoading(true);setMsg('');const r=await fetch('/api/super-admin-overview');const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.message||'Load failed');setData(j)}catch(e){setMsg(e.message||'Load failed')}finally{setLoading(false)}};useEffect(()=>{load()},[]);let page=view==='dashboard'?<Dashboard data={data} q={q}/>:view==='companies'?<Companies data={data} q={q}/>:view==='users-roles'?<Users data={data} q={q}/>:view==='demo-requests'?<Demos data={data} q={q}/>:view==='website-health'?<Health data={data} q={q}/>:<Generic view={view} data={data} q={q}/>;let m=meta[view]||meta.dashboard;return <div className="sf-dashboard sap2-root"><DashboardSidebar role="superAdmin"/><main className="sap2-main"><header className="sap2-top"><div><span>SalesFlow Hub · Super Admin</span><h1>{m[0]}</h1><p>{m[1]}</p></div><label><b>⌕</b><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search companies, users, emails..."/></label><button onClick={load}>{loading?'Loading...':'Refresh'}</button></header><nav className="sap2-tabs">{['dashboard','companies','users-roles','demo-requests','website-health','leads-monitor'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}>{v.replace('-',' ')}</button>)}</nav>{msg&&<div className="sap2-msg">{msg}</div>}{page}</main></div>}
