import { useEffect, useMemo, useState } from 'react';
import { LayoutDashboard, Building2, Users, CreditCard, TrendingUp, Target, Bell, Mail, ShieldCheck, Settings, Search, HelpCircle, BarChart2, ClipboardList, Headphones, Menu, Globe, RefreshCw, LogOut, CheckCircle2, Clock, CalendarCheck, Activity, Server, Zap, ArrowUpRight, MoreHorizontal } from 'lucide-react';
import { AreaChart, Area, BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const navItems = [
  ['Overview', 'dashboard', LayoutDashboard],
  ['Companies', 'companies', Building2],
  ['Users & Roles', 'users', Users],
  ['Subscriptions', 'subscriptions', CreditCard],
  ['Revenue & Plans', 'revenue', TrendingUp],
  ['Leads Monitor', 'leads', Target],
  ['Notifications', 'notifications', Bell, 12],
  ['Email Logs', 'email-logs', Mail],
  ['Security', 'security', ShieldCheck],
  ['Platform Settings', 'platform', Settings],
  ['Reports', 'reports', BarChart2],
  ['Activity Logs', 'activity-logs', ClipboardList],
  ['Support Tickets', 'support-tickets', Headphones],
  ['Website Health', 'website-health', Globe, 4],
];

const themeCss = `
:root{--background:222 47% 9%;--foreground:210 40% 96%;--card:222 47% 12%;--card-foreground:210 40% 96%;--card-border:222 47% 18%;--border:222 47% 18%;--sidebar:222 47% 7%;--sidebar-foreground:210 40% 96%;--sidebar-border:222 47% 14%;--sidebar-primary:217 91% 60%;--sidebar-primary-foreground:222 47% 9%;--sidebar-accent:222 47% 15%;--sidebar-accent-foreground:210 40% 96%;--primary:217 91% 60%;--primary-foreground:222 47% 9%;--secondary:222 47% 18%;--secondary-foreground:210 40% 96%;--muted:222 47% 16%;--muted-foreground:215 20% 55%;--accent:222 47% 20%;--accent-foreground:210 40% 96%;--input:222 47% 22%;--ring:217 91% 60%}
.sf-exact-app{min-height:100vh;background:hsl(var(--background));color:hsl(var(--foreground));font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;display:flex;overflow:hidden}.sf-exact-sidebar{width:220px;min-width:220px;background:hsl(var(--sidebar));border-right:1px solid hsl(var(--sidebar-border));height:100vh;position:fixed;left:0;top:0;z-index:50;display:flex;flex-direction:column}.sf-exact-brand{height:64px;padding:0 16px;display:flex;align-items:center;border-bottom:1px solid hsl(var(--sidebar-border))}.sf-exact-main{margin-left:220px;min-width:0;flex:1;height:100vh;overflow:auto;background:hsl(var(--background))}.sf-exact-topbar{height:64px;border-bottom:1px solid hsl(var(--border));background:hsl(var(--card));display:flex;align-items:center;justify-content:space-between;padding:0 20px;position:sticky;top:0;z-index:40}.sf-exact-card{background:hsl(var(--card));border:1px solid hsl(var(--card-border));border-radius:12px;box-shadow:none}.sf-exact-table th{font-size:12px;color:hsl(var(--muted-foreground));text-transform:uppercase;letter-spacing:.04em;text-align:left;padding:12px 16px}.sf-exact-table td{padding:14px 16px;border-top:1px solid hsl(var(--border));font-size:14px}.sf-badge{display:inline-flex;align-items:center;border-radius:999px;padding:3px 10px;font-size:12px;font-weight:700}.sf-badge.blue{background:rgba(59,130,246,.16);color:#93c5fd}.sf-badge.green{background:rgba(34,197,94,.16);color:#86efac}.sf-badge.orange{background:rgba(245,158,11,.16);color:#fbbf24}.sf-badge.red{background:rgba(239,68,68,.16);color:#fca5a5}.sf-exact-nav button{width:100%;display:flex;align-items:center;gap:12px;padding:8px 12px;border-radius:6px;color:hsl(var(--muted-foreground));font-size:14px;font-weight:600;background:transparent;border:0;cursor:pointer;transition:.15s}.sf-exact-nav button:hover{background:hsl(var(--sidebar-accent));color:hsl(var(--foreground))}.sf-exact-nav button.active{background:rgba(59,130,246,.15);color:hsl(var(--primary))}.sf-exact-scroll::-webkit-scrollbar,.sf-exact-sidebar nav::-webkit-scrollbar{width:8px}.sf-exact-scroll::-webkit-scrollbar-thumb,.sf-exact-sidebar nav::-webkit-scrollbar-thumb{background:#334155;border-radius:999px}@media(max-width:900px){.sf-exact-sidebar{display:none}.sf-exact-main{margin-left:0}.sf-grid-4{grid-template-columns:1fr!important}.sf-grid-2{grid-template-columns:1fr!important}}
`;

function injectTheme(){
  document.documentElement.classList.add('dark');
  if(!document.getElementById('sf-exact-theme')){const s=document.createElement('style');s.id='sf-exact-theme';s.textContent=themeCss;document.head.appendChild(s)}
  if(!document.getElementById('sf-tailwind-cdn')){window.tailwind={config:{darkMode:'class'}};const t=document.createElement('script');t.id='sf-tailwind-cdn';t.src='https://cdn.tailwindcss.com';document.head.appendChild(t)}
}

const money=(n)=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const date=(v)=>v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-';
const tone=(v='')=>{const x=String(v).toLowerCase();if(/active|paid|up|delivered|resolved|converted/.test(x))return'green';if(/trial|pending|open|medium|scheduled|degraded/.test(x))return'orange';if(/failed|down|suspended|expired|high|urgent|rejected/.test(x))return'red';return'blue'};
function Badge({label}){return <span className={`sf-badge ${tone(label)}`}>{label||'-'}</span>}
function StatCard({title,value,subtitle,icon:Icon}){return <div className="sf-exact-card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium" style={{color:'hsl(var(--muted-foreground))'}}>{title}</p><p className="text-2xl font-bold mt-2">{value}</p>{subtitle&&<p className="text-xs mt-1" style={{color:'hsl(var(--muted-foreground))'}}>{subtitle}</p>}</div><div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{background:'rgba(59,130,246,.16)',color:'#60a5fa'}}><Icon className="w-5 h-5"/></div></div></div>}
function Table({heads,rows,render}){return <div className="sf-exact-card overflow-hidden"><div className="overflow-x-auto"><table className="sf-exact-table w-full"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(render):<tr><td colSpan={heads.length}>No records found.</td></tr>}</tbody></table></div></div>}
function Header({title,subtitle,action}){return <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">{title}</h1>{subtitle&&<p className="text-sm mt-1" style={{color:'hsl(var(--muted-foreground))'}}>{subtitle}</p>}</div>{action}</div>}

function normalize(api){
 const companies=(api.companies||[]).map((c,i)=>({id:c.id||i,name:c.name||'Company',owner:c.adminEmail||c.admin_email||'-',plan:c.plan||'Trial',status:c.status||'Trial',users:c.users||0,mrr:c.mrr||0,createdAt:c.createdAt||c.created_at}));
 const users=(api.recentUsers||[]).map((u,i)=>({id:u.id||i,name:u.name||'User',email:u.email||'-',company:u.companyName||'-',role:u.role||'Employee',plan:u.plan||(u.isActive?'Professional':'Trial'),status:u.isActive?'Active':'Trial',lastLogin:u.createdAt,createdAt:u.createdAt}));
 const demos=(api.demoRequests||[]).map((d,i)=>({id:d.id||i,name:d.fullName||'Visitor',email:d.email||'-',phone:d.mobile||'-',company:d.companyName||'-',teamSize:d.teamSize||'-',requirement:d.requirement||'-',preferredTime:d.preferredTime||'-',status:d.status||'Pending',createdAt:d.createdAt}));
 const health=(api.websiteHealth||[]).map((h,i)=>({id:h.id||i,company:h.company,url:h.url,status:h.status||'Up',latency:h.responseTime||h.latency||142,uptime:h.uptime||'99.98%',ssl:h.ssl||'Valid'}));
 return{companies,users,demos,health,logs:api.activityLogs||[],emails:api.emailLogs||[],tickets:api.supportTickets||[],stats:api.stats||{},growth:api.growth?.length?api.growth:[{month:'Jan',mrr:12000,users:8},{month:'Feb',mrr:22000,users:14},{month:'Mar',mrr:31000,users:18},{month:'Apr',mrr:42000,users:24},{month:'May',mrr:59000,users:32},{month:'Jun',mrr:78000,users:44}]}
}
function seed(){return normalize({companies:[{name:'Accomation',adminEmail:'hello@salesflowhub.cloud',plan:'Professional',status:'Active',users:4,mrr:4999}],recentUsers:[{name:'Super Admin',email:'hello@salesflowhub.cloud',companyName:'SalesFlow Hub',role:'Super Admin',isActive:true,createdAt:new Date().toISOString()}],stats:{activeUsers:1,monthlyRevenue:4999,uptime:'99.98%'},websiteHealth:[{company:'SalesFlow Hub',url:'salesflowhub.cloud',status:'Up',responseTime:142,uptime:'99.98%'}]})}

function Sidebar({page,setPage}){return <aside className="sf-exact-sidebar"><div className="sf-exact-brand"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0" style={{background:'hsl(var(--primary))',color:'hsl(var(--primary-foreground))'}}><span className="text-xs font-bold">SH</span></div><div className="flex flex-col leading-tight"><span className="text-sm font-bold">SalesFlow Hub</span><span className="text-[10px] font-medium uppercase tracking-widest" style={{color:'hsl(var(--muted-foreground))'}}>Super Admin</span></div></div></div><nav className="sf-exact-nav flex-1 py-3 px-2 space-y-0.5 overflow-y-auto">{navItems.map(([name,key,Icon,badge])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon className="w-4 h-4 shrink-0"/><span className="truncate">{name}</span>{badge&&<span className="ml-auto rounded-full text-[10px] px-1.5 h-5 min-w-[20px] flex items-center justify-center" style={{background:'hsl(var(--primary))',color:'hsl(var(--primary-foreground))'}}>{badge}</span>}</button>)}</nav><div className="p-4 border-t space-y-3" style={{borderColor:'hsl(var(--sidebar-border))'}}><div className="flex items-center gap-2 text-xs px-1" style={{color:'hsl(var(--muted-foreground))'}}><div className="w-2 h-2 rounded-full bg-green-500 shrink-0"></div><span>View Platform Status</span></div><div className="text-[10px] px-1 leading-relaxed" style={{color:'rgba(148,163,184,.55)'}}>© 2026 SalesFlow Hub<br/>All rights reserved.</div></div></aside>}
function Topbar(){return <header className="sf-exact-topbar"><div className="flex items-center gap-3 flex-1"><button className="text-muted-foreground"><Menu className="w-5 h-5"/></button><div className="relative flex-1 max-w-md hidden md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4" style={{color:'hsl(var(--muted-foreground))'}}/><input type="search" placeholder="Search companies, users, invoices, tickets..." className="w-full bg-background border pl-9 pr-12 rounded-lg h-9 text-sm outline-none" style={{borderColor:'hsl(var(--border))',color:'hsl(var(--foreground))'}}/></div></div><div className="flex items-center gap-2"><button className="relative p-2 rounded-lg hover:bg-muted"><Bell className="w-5 h-5"/><span className="absolute top-1 right-1 w-2 h-2 bg-primary rounded-full"/></button><button className="p-2 rounded-lg hover:bg-muted"><HelpCircle className="w-5 h-5"/></button><div className="flex items-center gap-2 ml-2"><div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center text-primary-foreground text-sm font-semibold">SA</div><div className="hidden lg:block leading-tight"><p className="text-sm font-medium">Super Admin</p><p className="text-xs" style={{color:'hsl(var(--muted-foreground))'}}>superadmin@salesflowhub.cloud</p></div></div></div></header>}
function Layout({page,setPage,children}){return <div className="sf-exact-app"><Sidebar page={page} setPage={setPage}/><main className="sf-exact-main sf-exact-scroll"><Topbar/>{children}</main></div>}

function Dashboard({d}){const s=d.stats;return <div className="p-6 space-y-6"><Header title="Dashboard" subtitle="Platform-wide overview and performance metrics" action={<button className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground px-4 py-2 text-sm font-medium">Export <ArrowUpRight className="w-4 h-4"/></button>}/><div className="sf-grid-4 grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Total Companies" value={d.companies.length} icon={Building2} subtitle="active tenants"/><StatCard title="Total Users" value={d.users.length} icon={Users} subtitle={`${s.activeUsers||0} active`}/><StatCard title="MRR" value={money(s.monthlyRevenue)} icon={CreditCard} subtitle="+12.5% from last month"/><StatCard title="Demo Requests" value={d.demos.length} icon={CalendarCheck} subtitle="new pipeline"/></div><div className="sf-grid-2 grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="sf-exact-card p-5"><h3 className="text-sm font-semibold mb-4">MRR Growth</h3><div className="h-64"><ResponsiveContainer><AreaChart data={d.growth}><defs><linearGradient id="mrr" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#60a5fa" stopOpacity={0.32}/><stop offset="95%" stopColor="#60a5fa" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(148,163,184,.18)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="mrr" stroke="#60a5fa" fill="url(#mrr)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="sf-exact-card p-5"><h3 className="text-sm font-semibold mb-4">User Growth</h3><div className="h-64"><ResponsiveContainer><BarChart data={d.growth}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(148,163,184,.18)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="users" fill="#60a5fa" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div></div><div className="sf-grid-2 grid grid-cols-1 lg:grid-cols-2 gap-4"><Table heads={['Company','Plan','Status','Users','MRR']} rows={d.companies.slice(0,6)} render={c=><tr key={c.id}><td className="font-semibold">{c.name}</td><td><Badge label={c.plan}/></td><td><Badge label={c.status}/></td><td>{c.users}</td><td>{money(c.mrr)}</td></tr>}/><Table heads={['Name','Company','Status','Time']} rows={d.demos.slice(0,6)} render={x=><tr key={x.id}><td className="font-semibold">{x.name}</td><td>{x.company}</td><td><Badge label={x.status}/></td><td>{date(x.createdAt)}</td></tr>}/></div></div>}
function Companies({d}){return <div className="p-6 space-y-6"><Header title="Companies" subtitle="All tenant companies and subscription status"/><div className="sf-grid-4 grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Companies" value={d.companies.length} icon={Building2}/><StatCard title="Active" value={d.companies.filter(c=>String(c.status).toLowerCase().includes('active')).length} icon={CheckCircle2}/><StatCard title="Trial" value={d.companies.filter(c=>String(c.status).toLowerCase().includes('trial')).length} icon={Clock}/><StatCard title="MRR" value={money(d.companies.reduce((a,c)=>a+(c.mrr||0),0))} icon={CreditCard}/></div><Table heads={['Company','Owner','Plan','Status','Users','MRR','Created']} rows={d.companies} render={c=><tr key={c.id}><td className="font-semibold">{c.name}</td><td>{c.owner}</td><td><Badge label={c.plan}/></td><td><Badge label={c.status}/></td><td>{c.users}</td><td>{money(c.mrr)}</td><td>{date(c.createdAt)}</td></tr>}/></div>}
function UsersPage({d}){return <div className="p-6 space-y-6"><Header title="Users & Roles" subtitle="All registered users across all companies"/><Table heads={['User','Company','Role','Plan','Status','Last Login','Joined']} rows={d.users} render={u=><tr key={u.id}><td><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-primary flex items-center justify-center text-primary-foreground font-bold text-xs">{String(u.name).slice(0,2).toUpperCase()}</div><div><p className="font-semibold">{u.name}</p><p className="text-xs" style={{color:'hsl(var(--muted-foreground))'}}>{u.email}</p></div></div></td><td>{u.company}</td><td><Badge label={u.role}/></td><td><Badge label={u.plan}/></td><td><Badge label={u.status}/></td><td>recently</td><td>{date(u.createdAt)}</td></tr>}/></div>}
function Subscriptions({d}){return <div className="p-6 space-y-6"><Header title="Subscriptions" subtitle="Billing and subscription management"/><Table heads={['Company','Plan','Status','MRR','Next Billing','Action']} rows={d.companies} render={c=><tr key={c.id}><td className="font-semibold">{c.name}</td><td><Badge label={c.plan}/></td><td><Badge label={c.status}/></td><td>{money(c.mrr)}</td><td>{date(c.createdAt)}</td><td><MoreHorizontal className="w-5 h-5"/></td></tr>}/></div>}
function Demos({d}){return <div className="p-6 space-y-6"><Header title="Demo Requests" subtitle="Incoming demo scheduling requests"/><Table heads={['Name','Email','Phone','Company','Team','Requirement','Preferred','Status']} rows={d.demos} render={x=><tr key={x.id}><td className="font-semibold">{x.name}</td><td>{x.email}</td><td>{x.phone}</td><td>{x.company}</td><td>{x.teamSize}</td><td>{x.requirement}</td><td>{x.preferredTime}</td><td><Badge label={x.status}/></td></tr>}/></div>}
function Health({d}){const hist=[{day:'Mon',uptime:99.8},{day:'Tue',uptime:99.9},{day:'Wed',uptime:99.7},{day:'Thu',uptime:99.98},{day:'Fri',uptime:99.99},{day:'Sat',uptime:99.95},{day:'Sun',uptime:99.98}];return <div className="p-6 space-y-6"><Header title="Website Health" subtitle="Real-time platform monitoring and system status"/><div className="sf-grid-4 grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Uptime" value={d.stats.uptime||'99.98%'} icon={HeartPulse}/><StatCard title="Avg Response" value="142ms" icon={Zap}/><StatCard title="Active Users" value={d.stats.activeUsers||0} icon={Activity}/><StatCard title="Error Rate" value="0.02%" icon={Server}/></div><div className="sf-exact-card p-5"><h3 className="text-sm font-semibold mb-4">7-Day Uptime History</h3><div className="h-48"><ResponsiveContainer><LineChart data={hist}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis domain={[99,100]}/><Tooltip/><Line type="monotone" dataKey="uptime" stroke="#22c55e" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div><Table heads={['Service','URL','Latency','Uptime','Status']} rows={d.health} render={s=><tr key={s.id}><td className="font-semibold">{s.company}</td><td>{s.url}</td><td>{s.latency}ms</td><td>{s.uptime}</td><td><Badge label={s.status}/></td></tr>}/></div>}
function Generic({title,d}){const rows=d.logs.length?d.logs:d.emails.length?d.emails:d.tickets;return <div className="p-6 space-y-6"><Header title={title} subtitle="Platform activity and operations"/><Table heads={['Title','Company','Status','Priority / Time']} rows={rows} render={(x,i)=><tr key={x.id||i}><td className="font-semibold">{x.title||x.type||x.subject||x.action||'-'}</td><td>{x.company||x.to||'-'}</td><td><Badge label={x.status||'Open'}/></td><td>{x.priority||x.time||'-'}</td></tr>}/></div>}
function Plans(){return <div className="p-6 space-y-6"><Header title="Plans" subtitle="Pricing plan management"/><div className="sf-grid-4 grid grid-cols-1 lg:grid-cols-3 gap-4">{[['Starter','₹0','Basic CRM features'],['Professional','₹4,999','Advanced teams and reports'],['Enterprise','Custom','White-label and priority support']].map(p=><div className="sf-exact-card p-6" key={p[0]}><h3 className="text-lg font-bold">{p[0]}</h3><p className="text-3xl font-bold mt-4">{p[1]}</p><p className="text-sm mt-2" style={{color:'hsl(var(--muted-foreground))'}}>{p[2]}</p><button className="mt-6 w-full rounded-md border px-4 py-2">Manage Plan</button></div>)}</div></div>}
export default function SuperAdminZipApp(){const[page,setPage]=useState('dashboard');const[data,setData]=useState(seed());useEffect(()=>{injectTheme();fetch('/api/super-admin-overview').then(r=>r.json()).then(j=>setData(normalize(j))).catch(()=>{})},[]);const view=useMemo(()=>({dashboard:<Dashboard d={data}/>,companies:<Companies d={data}/>,users:<UsersPage d={data}/>,subscriptions:<Subscriptions d={data}/>,revenue:<Dashboard d={data}/>,leads:<Generic title="Leads Monitor" d={data}/>,notifications:<Generic title="Notifications" d={data}/>,platform:<Generic title="Platform Settings" d={data}/>,reports:<Generic title="Reports" d={data}/>,security:<Generic title="Security" d={data}/>,plans:<Plans/>, 'demo-requests':<Demos d={data}/>, 'website-health':<Health d={data}/>, 'activity-logs':<Generic title="Activity Logs" d={data}/>, 'email-logs':<Generic title="Email Logs" d={data}/>, 'support-tickets':<Generic title="Support Tickets" d={data}/>})[page]||<Dashboard d={data}/>,[page,data]);return <Layout page={page} setPage={setPage}>{view}</Layout>}
