import { useEffect, useMemo, useState } from 'react';
import { LayoutDashboard, Building2, Users, CreditCard, Package, CalendarCheck, Activity, Mail, Ticket, HeartPulse, LogOut, Shield, Search, Bell, RefreshCw, MoreHorizontal, ArrowUpRight, Clock, CheckCircle2, XCircle, AlertTriangle, UserCheck, ShieldAlert, Zap, Server } from 'lucide-react';
import { AreaChart, Area, BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import './index.css';

const NAV = [
  { label: 'MAIN', items: [['dashboard', LayoutDashboard, 'Dashboard'], ['companies', Building2, 'Companies'], ['users', Users, 'Users']] },
  { label: 'BILLING', items: [['subscriptions', CreditCard, 'Subscriptions'], ['plans', Package, 'Plans']] },
  { label: 'OPERATIONS', items: [['demo-requests', CalendarCheck, 'Demo Requests'], ['support-tickets', Ticket, 'Support Tickets']] },
  { label: 'SYSTEM', items: [['website-health', HeartPulse, 'Website Health'], ['activity-logs', Activity, 'Activity Logs'], ['email-logs', Mail, 'Email Logs']] },
];

const money = (n) => `₹${Number(n || 0).toLocaleString('en-IN')}`;
const date = (v) => v ? new Date(v).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }) : '-';
const ago = (v) => v ? 'recently' : '-';
const badgeClass = (label = '') => {
  const x = String(label).toLowerCase();
  if (/active|paid|completed|operational|delivered|converted|resolved/.test(x)) return 'bg-emerald-100 text-emerald-700';
  if (/trial|pending|medium|open|scheduled/.test(x)) return 'bg-yellow-100 text-yellow-700';
  if (/failed|down|suspended|high|urgent|expired/.test(x)) return 'bg-red-100 text-red-700';
  if (/pro|enterprise/.test(x)) return 'bg-purple-100 text-purple-700';
  return 'bg-blue-100 text-blue-700';
};
function Badge({ label }) { return <span className={`badge ${badgeClass(label)}`}>{label}</span>; }
function StatCard({ title, value, icon: Icon, iconBg='bg-orange-100', iconColor='text-orange-600', subtitle, trend, trendUp }) { return <div className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-gray-500">{title}</p><p className="text-2xl font-bold text-gray-900 mt-2">{value}</p>{subtitle && <p className="text-xs text-gray-400 mt-1">{subtitle}</p>}{trend && <p className={`text-xs font-medium mt-1 ${trendUp ? 'text-emerald-600' : 'text-red-600'}`}>{trend}</p>}</div><div className={`w-10 h-10 rounded-lg ${iconBg} flex items-center justify-center`}><Icon className={`w-5 h-5 ${iconColor}`} /></div></div></div>; }
function PageHeader({ title, subtitle, action }) { return <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">{title}</h1>{subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}</div>{action}</div>; }
function Table({ heads, rows, render }) { return <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{heads.map(h => <th key={h} className="table-th">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map(render) : <tr><td className="table-td" colSpan={heads.length}>No records found.</td></tr>}</tbody></table></div></div>; }

function normalize(api) {
  const companies = (api.companies || []).map((c, i) => ({ id:c.id||i, name:c.name||'Company', owner:c.adminEmail||c.admin_email||'-', plan:c.plan||'Trial', status:c.status||'Trial', users:c.users||0, mrr:c.mrr||0, createdAt:c.createdAt||c.created_at }));
  const users = (api.recentUsers || []).map((u, i) => ({ id:u.id||i, name:u.name||u.full_name||'User', email:u.email||'-', company:u.companyName||'-', role:u.role||'Employee', plan:u.plan|| (u.isActive ? 'Pro' : 'Trial'), status:u.isActive ? 'Active' : 'Trial', joinedAt:u.createdAt, lastLogin:u.createdAt }));
  const demos = (api.demoRequests || []).map((d, i) => ({ id:d.id||i, name:d.fullName||'Visitor', email:d.email||'-', phone:d.mobile||'-', company:d.companyName||'-', teamSize:d.teamSize||'-', requirement:d.requirement||'-', preferredTime:d.preferredTime||'-', status:d.status||'Pending', createdAt:d.createdAt }));
  const health = api.websiteHealth || [];
  const logs = api.activityLogs || [];
  const emails = api.emailLogs || [];
  const tickets = api.supportTickets || [];
  return { companies, users, demos, health, logs, emails, tickets, stats: api.stats || {}, growth: api.growth || [] };
}

function seed() {
  const companies = [{id:1,name:'Accomation',owner:'hello@salesflowhub.cloud',plan:'Pro',status:'Active',users:4,mrr:4999,createdAt:new Date().toISOString()}];
  const users = [{id:1,name:'Super Admin',email:'hello@salesflowhub.cloud',company:'SalesFlow Hub',role:'Super Admin',plan:'Enterprise',status:'Active',joinedAt:new Date().toISOString(),lastLogin:new Date().toISOString()}];
  const demos = [];
  const health = [{id:1,company:'SalesFlow Website',url:'salesflowhub.cloud',status:'Operational',latency:142,uptime:99.98}];
  return { companies, users, demos, health, logs:[], emails:[], tickets:[], stats:{ totalCompanies:1,totalUsers:1,activeUsers:1,trialCompanies:0,paidCompanies:1,monthlyRevenue:4999,demoRequests:0,totalLeads:0,uptime:'99.98%' }, growth:[{month:'Jan',users:8,mrr:12000},{month:'Feb',users:14,mrr:22000},{month:'Mar',users:18,mrr:31000},{month:'Apr',users:24,mrr:42000},{month:'May',users:32,mrr:59000},{month:'Jun',users:44,mrr:78000}] };
}

function Sidebar({ page, setPage }) { return <aside className="fixed top-0 left-0 h-full w-64 bg-gray-900 flex flex-col z-30"><div className="flex items-center gap-3 px-5 py-5 border-b border-gray-800"><div className="w-9 h-9 rounded-lg bg-orange-500 flex items-center justify-center"><Shield className="w-5 h-5 text-white" /></div><div><p className="text-white font-bold text-sm leading-tight">SalesFlow Hub</p><p className="text-orange-400 text-xs font-semibold">Super Admin</p></div></div><nav className="flex-1 overflow-y-auto px-3 py-4 space-y-6">{NAV.map(g => <div key={g.label}><p className="text-gray-500 text-[10px] font-bold uppercase tracking-widest px-3 mb-2">{g.label}</p><div className="space-y-0.5">{g.items.map(([to, Icon, label]) => <button key={to} onClick={() => setPage(to)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors ${page === to ? 'bg-orange-500 text-white' : 'text-gray-400 hover:bg-gray-800 hover:text-white'}`}><Icon className="w-4 h-4" />{label}</button>)}</div></div>)}</nav><div className="px-3 py-4 border-t border-gray-800"><div className="flex items-center gap-3 px-3 py-2.5 rounded-lg bg-gray-800 mb-2"><div className="w-8 h-8 rounded-full bg-orange-500 flex items-center justify-center text-white font-bold text-xs">SA</div><div className="min-w-0"><p className="text-white text-sm font-medium truncate">Super Admin</p><p className="text-gray-400 text-xs truncate">admin@salesflowhub.com</p></div></div><button className="flex items-center gap-2 w-full px-3 py-2 text-gray-400 hover:text-red-400 text-sm font-medium rounded-lg hover:bg-gray-800"><LogOut className="w-4 h-4" />Logout</button></div></aside>; }
function Topbar({ title, subtitle }) { return <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between sticky top-0 z-20"><div><h1 className="text-xl font-bold text-gray-900">{title}</h1>{subtitle && <p className="text-sm text-gray-500 mt-0.5">{subtitle}</p>}</div><div className="flex items-center gap-3"><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400" /><input placeholder="Search..." className="pl-9 pr-4 py-2 text-sm bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 w-56" /></div><button className="relative p-2 text-gray-500 hover:bg-gray-100 rounded-lg"><Bell className="w-5 h-5" /><span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full" /></button><button className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg"><RefreshCw className="w-5 h-5" /></button></div></header>; }
function Layout({ page, setPage, children }) { const labels = {dashboard:'Dashboard',companies:'Companies',users:'Users',subscriptions:'Subscriptions',plans:'Plans','demo-requests':'Demo Requests','website-health':'Website Health','activity-logs':'Activity Logs','email-logs':'Email Logs','support-tickets':'Support Tickets'}; return <div className="flex h-screen overflow-hidden bg-gray-50"><Sidebar page={page} setPage={setPage}/><main className="flex-1 ml-64 overflow-y-auto"><Topbar title={labels[page] || 'Dashboard'} subtitle="SalesFlow Hub Super Admin" />{children}</main></div>; }

function Dashboard({ d }) { const s = d.stats; return <div className="p-6 space-y-6"><PageHeader title="Dashboard" subtitle="Platform-wide overview and performance metrics" action={<button className="btn-primary flex items-center gap-2">Export <ArrowUpRight className="w-4 h-4" /></button>} /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Total Companies" value={d.companies.length} icon={Building2} iconBg="bg-blue-100" iconColor="text-blue-600" subtitle="active tenants" /><StatCard title="Total Users" value={d.users.length} icon={Users} iconBg="bg-emerald-100" iconColor="text-emerald-600" subtitle={`${s.activeUsers||0} active`} /><StatCard title="MRR" value={money(s.monthlyRevenue)} icon={CreditCard} iconBg="bg-orange-100" iconColor="text-orange-600" trend="+12.5% from last month" trendUp /><StatCard title="Demo Requests" value={d.demos.length} icon={CalendarCheck} iconBg="bg-purple-100" iconColor="text-purple-600" subtitle="new pipeline" /></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="card p-5"><h3 className="text-sm font-semibold text-gray-900 mb-4">MRR Growth</h3><div className="h-64"><ResponsiveContainer><AreaChart data={d.growth}><defs><linearGradient id="mrr" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#f97316" stopOpacity={0.3}/><stop offset="95%" stopColor="#f97316" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="mrr" stroke="#f97316" fill="url(#mrr)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="card p-5"><h3 className="text-sm font-semibold text-gray-900 mb-4">User Growth</h3><div className="h-64"><ResponsiveContainer><BarChart data={d.growth}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="users" fill="#fb923c" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Table heads={['Company','Plan','Status','Users','MRR']} rows={d.companies.slice(0,5)} render={c => <tr key={c.id} className="table-tr"><td className="table-td font-semibold">{c.name}</td><td className="table-td"><Badge label={c.plan}/></td><td className="table-td"><Badge label={c.status}/></td><td className="table-td">{c.users}</td><td className="table-td">{money(c.mrr)}</td></tr>} /><Table heads={['Name','Company','Status','Time']} rows={d.demos.slice(0,5)} render={x => <tr key={x.id} className="table-tr"><td className="table-td font-semibold">{x.name}</td><td className="table-td">{x.company}</td><td className="table-td"><Badge label={x.status}/></td><td className="table-td">{date(x.createdAt)}</td></tr>} /></div></div>; }
function Companies({ d }) { return <div className="p-6 space-y-6"><PageHeader title="Companies" subtitle="All tenant companies and subscription status" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Companies" value={d.companies.length} icon={Building2} iconBg="bg-blue-100" iconColor="text-blue-600"/><StatCard title="Active" value={d.companies.filter(c=>c.status==='Active'||c.status==='active').length} icon={CheckCircle2} iconBg="bg-emerald-100" iconColor="text-emerald-600"/><StatCard title="Trial" value={d.companies.filter(c=>String(c.status).toLowerCase().includes('trial')).length} icon={Clock} iconBg="bg-yellow-100" iconColor="text-yellow-600"/><StatCard title="MRR" value={money(d.companies.reduce((a,c)=>a+(c.mrr||0),0))} icon={CreditCard}/></div><Table heads={['Company','Owner','Plan','Status','Users','MRR','Created']} rows={d.companies} render={c => <tr key={c.id} className="table-tr"><td className="table-td font-semibold text-gray-900">{c.name}</td><td className="table-td">{c.owner}</td><td className="table-td"><Badge label={c.plan}/></td><td className="table-td"><Badge label={c.status}/></td><td className="table-td">{c.users}</td><td className="table-td">{money(c.mrr)}</td><td className="table-td">{date(c.createdAt)}</td></tr>} /></div>; }
function UsersPage({ d }) { return <div className="p-6 space-y-6"><PageHeader title="Users" subtitle="All registered users across all companies" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Total Users" value={d.users.length} icon={Users} iconBg="bg-blue-100" iconColor="text-blue-600"/><StatCard title="Active" value={d.users.filter(u=>u.status==='Active').length} icon={UserCheck} iconBg="bg-emerald-100" iconColor="text-emerald-600"/><StatCard title="On Trial" value={d.users.filter(u=>u.status==='Trial').length} icon={Clock} iconBg="bg-yellow-100" iconColor="text-yellow-600"/><StatCard title="Suspended" value={d.users.filter(u=>u.status==='Suspended').length} icon={ShieldAlert} iconBg="bg-red-100" iconColor="text-red-600"/></div><Table heads={['User','Company','Role','Plan','Status','Last Login','Joined']} rows={d.users} render={u => <tr key={u.id} className="table-tr"><td className="table-td"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-orange-500 flex items-center justify-center text-white font-bold text-xs">{String(u.name).slice(0,2).toUpperCase()}</div><div><p className="font-semibold text-gray-900">{u.name}</p><p className="text-xs text-gray-400">{u.email}</p></div></div></td><td className="table-td">{u.company}</td><td className="table-td"><span className="bg-gray-100 text-gray-600 badge">{u.role}</span></td><td className="table-td"><Badge label={u.plan}/></td><td className="table-td"><Badge label={u.status}/></td><td className="table-td text-gray-400">{ago(u.lastLogin)}</td><td className="table-td text-gray-400">{date(u.joinedAt)}</td></tr>} /></div>; }
function Subscriptions({ d }) { return <div className="p-6 space-y-6"><PageHeader title="Subscriptions" subtitle="Billing and subscription management" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="MRR" value={money(d.stats.monthlyRevenue)} icon={CreditCard}/><StatCard title="Paid" value={d.companies.filter(c=>String(c.plan).toLowerCase()!=='trial').length} icon={CheckCircle2} iconBg="bg-emerald-100" iconColor="text-emerald-600"/><StatCard title="Trial" value={d.companies.filter(c=>String(c.plan).toLowerCase()==='trial').length} icon={Clock} iconBg="bg-yellow-100" iconColor="text-yellow-600"/><StatCard title="Expired" value="0" icon={XCircle} iconBg="bg-red-100" iconColor="text-red-600"/></div><Table heads={['Company','Plan','Status','MRR','Next Billing','Action']} rows={d.companies} render={c => <tr key={c.id} className="table-tr"><td className="table-td font-semibold">{c.name}</td><td className="table-td"><Badge label={c.plan}/></td><td className="table-td"><Badge label={c.status}/></td><td className="table-td">{money(c.mrr)}</td><td className="table-td">{date(c.createdAt)}</td><td className="table-td"><MoreHorizontal className="w-5 h-5 text-gray-400" /></td></tr>} /></div>; }
function Plans() { const plans=[['Starter','₹0','Basic CRM features','Active'],['Professional','₹4,999','Advanced teams and reports','Active'],['Enterprise','Custom','White-label and priority support','Active']]; return <div className="p-6 space-y-6"><PageHeader title="Plans" subtitle="Pricing plan management" /><div className="grid grid-cols-1 lg:grid-cols-3 gap-4">{plans.map(p => <div className="card p-6" key={p[0]}><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-gray-900">{p[0]}</h3><Badge label={p[3]}/></div><p className="text-3xl font-bold mt-4">{p[1]}</p><p className="text-sm text-gray-500 mt-2">{p[2]}</p><button className="btn-outline mt-6 w-full">Manage Plan</button></div>)}</div></div>; }
function Demos({ d }) { return <div className="p-6 space-y-6"><PageHeader title="Demo Requests" subtitle="Incoming demo scheduling requests" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Total Requests" value={d.demos.length} icon={CalendarCheck}/><StatCard title="Pending" value={d.demos.filter(x=>String(x.status).toLowerCase().includes('new')||String(x.status).toLowerCase().includes('pending')).length} icon={Clock} iconBg="bg-yellow-100" iconColor="text-yellow-600"/><StatCard title="Scheduled" value={d.demos.filter(x=>String(x.status).toLowerCase().includes('scheduled')).length} icon={CheckCircle2} iconBg="bg-emerald-100" iconColor="text-emerald-600"/><StatCard title="Converted" value={d.demos.filter(x=>String(x.status).toLowerCase().includes('converted')).length} icon={Users} iconBg="bg-purple-100" iconColor="text-purple-600"/></div><Table heads={['Name','Email','Phone','Company','Team','Requirement','Preferred','Status']} rows={d.demos} render={x => <tr key={x.id} className="table-tr"><td className="table-td font-semibold">{x.name}</td><td className="table-td">{x.email}</td><td className="table-td">{x.phone}</td><td className="table-td">{x.company}</td><td className="table-td">{x.teamSize}</td><td className="table-td">{x.requirement}</td><td className="table-td">{x.preferredTime}</td><td className="table-td"><Badge label={x.status}/></td></tr>} /></div>; }
function Health({ d }) { const hist=[{day:'Mon',uptime:99.8},{day:'Tue',uptime:99.9},{day:'Wed',uptime:99.7},{day:'Thu',uptime:99.98},{day:'Fri',uptime:99.99},{day:'Sat',uptime:99.95},{day:'Sun',uptime:99.98}]; return <div className="p-6 space-y-6"><PageHeader title="Website Health" subtitle="Real-time platform monitoring and system status" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard title="Uptime" value={`${d.stats.uptime||'99.98%'}`} icon={HeartPulse} iconBg="bg-emerald-100" iconColor="text-emerald-600" trend="Last 30 days" trendUp/><StatCard title="Avg Response" value="142ms" icon={Zap} iconBg="bg-blue-100" iconColor="text-blue-600"/><StatCard title="Active Users" value={(d.stats.activeUsers||0).toLocaleString()} icon={Activity} iconBg="bg-purple-100" iconColor="text-purple-600"/><StatCard title="Error Rate" value="0.02%" icon={Server} iconBg="bg-orange-100" iconColor="text-orange-600"/></div><div className="card p-5"><h3 className="text-sm font-semibold text-gray-900 mb-4">7-Day Uptime History</h3><div className="h-48"><ResponsiveContainer><LineChart data={hist}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis domain={[99,100]}/><Tooltip/><Line type="monotone" dataKey="uptime" stroke="#10b981" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div><Table heads={['Service','URL','Latency','Uptime','Status']} rows={d.health.length ? d.health : [{id:1,company:'SalesFlow Website',url:'salesflowhub.cloud',latency:142,uptime:99.98,status:'Operational'}]} render={s => <tr key={s.id} className="table-tr"><td className="table-td font-semibold">{s.company}</td><td className="table-td">{s.url}</td><td className="table-td">{s.latency||s.responseTime||142}ms</td><td className="table-td">{s.uptime}%</td><td className="table-td"><Badge label={s.status || 'Operational'}/></td></tr>} /></div>; }
function Logs({ d, type }) { const rows = type==='email-logs'?d.emails:type==='support-tickets'?d.tickets:d.logs; const title = type==='email-logs'?'Email Logs':type==='support-tickets'?'Support Tickets':'Activity Logs'; return <div className="p-6 space-y-6"><PageHeader title={title} subtitle="Platform activity and operations" /><Table heads={['Title','Company','Status','Priority/Time']} rows={rows} render={(x,i)=><tr key={x.id||i} className="table-tr"><td className="table-td font-semibold">{x.title||x.type||x.subject||x.action||'-'}</td><td className="table-td">{x.company||x.to||'-'}</td><td className="table-td"><Badge label={x.status||'Open'}/></td><td className="table-td">{x.priority||x.time||'-'}</td></tr>} /></div>; }

export default function SuperAdminZipApp() {
  const [page, setPage] = useState('dashboard');
  const [data, setData] = useState(seed());
  useEffect(() => { if (!document.getElementById('sf-tailwind-cdn')) { const s=document.createElement('script'); s.id='sf-tailwind-cdn'; s.src='https://cdn.tailwindcss.com'; document.head.appendChild(s); } fetch('/api/super-admin-overview').then(r=>r.json()).then(j=>setData(normalize(j))).catch(()=>{}); }, []);
  const view = useMemo(() => ({ dashboard:<Dashboard d={data}/>, companies:<Companies d={data}/>, users:<UsersPage d={data}/>, subscriptions:<Subscriptions d={data}/>, plans:<Plans/>, 'demo-requests':<Demos d={data}/>, 'website-health':<Health d={data}/>, 'activity-logs':<Logs d={data} type="activity-logs"/>, 'email-logs':<Logs d={data} type="email-logs"/>, 'support-tickets':<Logs d={data} type="support-tickets"/> })[page] || <Dashboard d={data}/>, [page, data]);
  return <Layout page={page} setPage={setPage}>{view}</Layout>;
}
